### ISSUE TITLE
Sanitation problem

### ISSUE THREAD

**Issue by CalebMacdonaldBlack** [temowemo/temowemo#1]
Sanitation needs to be done server side. I can just send a POST request to http://rest.learncode.academy/api/temo/comments with whatever text I want. Also, replace the '<' and '>' with empty strings because I can still do this "< script>alert('hax')</ script>".

**Comment by temowemo** [comment]
Hahaha i know man, I haven't really bothered with trying to stop XSS other than that small piece of code.. I guess i will now or I will look like an idiot to potential employers. As for authentication, I am not going to implement that on this website yet because it has a php backend and i am using a public api database.

**Comment by temowemo** [comment]
But now I fixed it. Go ahead and try to do it again haha.
